apiVersion: v1
kind: Pod
metadata:
  name: k6
  namespace: motivation
spec:
  restartPolicy: Never
  containers:
    - name: k6
      image: grafana/k6:2.1.0
      command:
        - /bin/sh
        - -c
        - sleep 7200
      env:
        - name: TARGET_URL
          value: http://boutique-router:80
      volumeMounts:
        - name: script
          mountPath: /scripts
          readOnly: true
        - name: results
          mountPath: /results
  volumes:
    - name: script
      configMap:
        name: k6-script
    - name: results
      emptyDir: {}
