apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: online-boutique-duplicated
  namespace: motivation
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
    - apiVersion: v1
      kind: Service
    - apiVersion: v1
      kind: ConfigMap
    - apiVersion: v1
      kind: Secret
    - apiVersion: v1
      kind: ServiceAccount
  propagateDeps: true
  conflictResolution: Abort
  placement:
    clusterAffinity:
      clusterNames:
        - cluster1
        - cluster2
    spreadConstraints:
      - spreadByField: cluster
        minGroups: 2
        maxGroups: 2
    replicaScheduling:
      replicaSchedulingType: Duplicated
